[phases.setup]
nixPkgs = ["php82", "nginx", "libmysqlclient", "phpPackages.composer", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "echo '🚀 Starting build process...'",
    "touch database/database.sqlite",
    "chmod 666 database/database.sqlite",
    "php artisan config:clear",
    "echo '🔒 Setting permissions for storage and cache...'",
    "chmod -R 775 storage bootstrap/cache",
    "php artisan migrate --force",
    "echo '✅ Build process complete.'"
]
