[phases.setup]
nixPkgs = ["php81", "nginx", "libmysqlclient", "phpPackages.composer", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = []

[start]
cmd = "./railway-start.sh"